# -*- coding: utf-8 -*-
# 필러·연결어 배치 4 (2026-09-29) — 회화 교정 3~4단계 30장 (91~120번째)
# ⚠️ 리듬맵에 `**` 가 하나라도 생기면 capsToStress 의 맨대문자 자동 변환이 꺼진다.
#    필러를 `**` 로 넣는 순간, 원래 맨대문자였던 피크(SOON·GEAR·NETflix …)를 전부 `**` 로 감싸야 한다.
B4 = [
("JxOx4DH7Gjx4vHGipTat","Yeah,",
 "Yeah, I'm staying for four nights and five days.",
 "Yeah, ↘↗ / I'm **stay**ing for **four** nights → / and **FIVE** days. ↘",
 "예, / 아임 **s떼이**잉 f어r **f오-r** 나잇츠 / 앤드 **f아이v** 데이z.",
 "네, 4박 5일로 머물러요."),
("NJWyiUlsRuxY2raKUGo0","Actually,",
 "Actually, I've been to Thailand twice. I went to Bangkok both times.",
 "**Ac**tually, ↘↗ / I've **been** to **Thai**land **TWICE**. ↘ I went to **Bang**kok → / **both** times. ↘",
 "**액**츄얼리, / 아이v **빈** 투 **타**일런d **트와이s**. 아이 웬투 **방**칵 / **보우ㅆ** 타임z.",
 "사실 태국에는 두 번 가봤어요. 두 번 다 방콕에 갔어요."),
("QwqBGPYaMxzCFjUSEuMB","Oh,",
 "Oh, I'm going with two of my staff.",
 "**Oh**, ↘↗ / I'm **go**ing with **two** of my **STAFF**. ↘",
 "**오**우, / 아임 **고**우잉 위ㄷ **투-** 어v 마이 **s태f**.",
 "아, 직원 두 명과 같이 가요."),
("cfsMFwqcLiQbEQJmbunD","So",
 "So I heard Da Nang has a lot of Korean restaurants and cafés. Some people call it a little Korea.",
 "**So** ↘↗ / I **heard** Da Nang has a **lot** of Ko**re**an restaurants and ca**fés**. ↘ Some people **call** it a **lit**tle Ko**RE**a. ↘",
 "**쏘**우 / 아이 **허-rd** 다낭 해z 얼**라**러v 커**뤼**-언 뤠s추란츠 앤드 캐**f에**이z. 썸 피뽈 **커어**릿 얼**리**를 커**뤼**-어.",
 "그게, 다낭에는 한국 식당이랑 카페가 많다고 들었어요. 어떤 사람들은 거기를 리틀 코리아라고 부르더라고요."),
("8yI3FsFgHg1W2KfznQLS","Honestly,",
 "Honestly, after the handover, I'd like some rest, but I've already signed contracts and I have a lot of work to do.",
 "**Hon**estly, ↘↗ / after the **hand**over, ↘↗ / I'd **like** some rest, ↗ but I've al**rea**dy signed **con**tracts ↗ and I have a **LOT** of work to do. ↘",
 "**아**너s리, / 애f터r 더 **핸**도우v어r, / 아이d **라익** 섬 레sㅌ, / 벝 아이v 얼**레**리 싸인d **컨**트뤡츠 / 앤드 아이 해v 어 **랕** 어v 워-rㅋ 투 두-.",
 "솔직히 인계가 끝나면 좀 쉬고 싶은데, 이미 계약을 여러 건 체결해서 할 일이 많아요."),
("CdUVIfICvtKRn4ZkNtc0","Okay, so",
 "Okay, so first I'll go through the issues, then talk with our engineer to see whether we can handle it in-house or not.",
 "O**kay**, ↘↗ / so **first** ↘↗ / I'll go **through** the **is**sues, ↗ then **talk** with our en**gi**neer → / to see whether we can **han**dle it in-**HOUSE** or not. ↘",
 "오우**케**이, / 쏘우 **f어rsㅌ** / 아일 고우 **쓰루** 디 **이**슈z, / 덴 **톡** 위드 아워r **엔**쥐니어r / 투 씨- 웨더r 위 캔 **핸**들 잍 인-**하우s** 오r 낱.",
 "네, 그럼 먼저 이슈들을 살펴보고, 그다음에 저희 엔지니어와 이야기해서 자체적으로 처리할 수 있을지 확인해볼게요."),
("JScL8Qo9XhO3uOYmIfP7","And",
 "And if we can't handle it, we'll bring in an outside contractor.",
 "**And** ↘↗ / if we **can't** handle it, ↘↗ / we'll **bring** in → / an outside con**TRAC**tor. ↘",
 "**앤**드 / 이f 위 **캔ㅌ** 핸들 잍, / 위을 **브링** 인 / 언 아웃싸이d 컨**츄랙**터r.",
 "그리고 저희가 처리할 수 없으면 외부 시공사를 부를 거예요."),
("Qou8L4dcjTxHtOzlBPYP","Yeah, / aqualink → Aqualink · have to → gotta",
 "Yeah, today we prepared for the handover. We had a meeting with Aqualink to go over some issues and their requests, so this week we gotta make a few decisions.",
 "Yeah, ↘↗ / to**day** ↘↗ / we pre**pared** → / for the **hand**over. ↘ We had a **meet**ing → / with **A**qualink → to go **o**ver some **is**sues ↗ / and their re**quests**, → so this **week** → / we **got**ta make a few de**CI**sions. ↓",
 "예, / 투**데**이 / 위 프리**페어rd** / f어r 더 **핸**도우v어r. 위 해더 **미-**링 / 위드 **아**콰링ㅋ / 투 고우 **오**우v어r 섬 **이**슈z / 앤드 데어r 리**퀘s**츠, / 소우 디s **위-ㅋ** / 위 **가**라 메이커 f유- 디**씨**전z.",
 "네, 오늘은 인계 준비를 했어요. Aqualink와 미팅을 해서 몇 가지 이슈와 요청 사항을 검토했고, 그래서 이번 주에 몇 가지를 결정해야 해요."),
("q6K0YTiZVWMHnLV5Ax23","So",
 "So they wanted to relocate some of the water pipe connections.",
 "**So** ↘↗ / they **wan**ted to relo**cate** → / some of the **wa**ter pipe con**NEC**tions. ↘",
 "**쏘**우 / 데이 **워니**d 투 뤼로우**케이ㅌ** / 섬 어v 더 **와러r** 파입 커**넥**션z.",
 "그러니까 그쪽에서 수도 배관 연결부 일부를 옮기고 싶어 했어요."),
("uf2HSWXI4sS7MeGcRc2l","Well, / because → 'cause · need to → gotta",
 "Well, I said I couldn't decide right now 'cause we gotta check with the BFP first.",
 "**Well**, ↘↗ / I said I **could**n't de**cide** right now → 'cause we **got**ta **CHECK** → / with the **BFP** first. ↓",
 "**웰**, / 아이 세d 아이 **쿠**른ㅌ 디**싸이d** 롸잍 나우 / 커z 위 **가**라 **첵** / 위드 더 **비-에f피** f어rsㅌ.",
 "음, 먼저 소방청(BFP)에 확인해야 해서 지금 당장은 결정할 수 없다고 말했어요."),
("0pxwdDz9nPgvkqZ7JaRP","So / need to → gotta",
 "So we gotta figure out if there's anything wrong, and check whether their plans have any issues or not.",
 "**So** ↘↗ / we **got**ta **fi**gure out → / if there's **a**nything **wrong**, ↗ and check **whe**ther their **plans** → / have any **IS**sues or not. ↓",
 "**쏘**우 / 위 **가**라 **f이**규어r 아웉 / 이f 데어r z **에**니씽 **롱**, / 앤드 첵 **웨**더r 데어r **플랜z** / 해v 에니 **이**슈z 오r 낱.",
 "그러니까 뭔가 잘못된 게 있는지 파악하고, 그쪽 도면에 문제가 있는지 없는지 확인해야 해요."),
("3fNe5EycChNW6Js58VZK","Honestly, / I mean,",
 "Honestly, I was pretty busy today. I mean, I had a lot to do.",
 "**Hon**estly, ↘↗ / I was **pretty BUSY** today. ↘ I **mean**, ↘↗ / I had a **LOT** to do. ↘",
 "**아**너s리, / 아이 워z **프뤼리 비지** 터데이. 아이 **미**-ㄴ, / 아이 해러 **랏** 터 두.",
 "솔직히 오늘은 꽤 바빴어요. 그러니까, 할 일이 많았거든요."),
("H54FFFIfZYjfKbU2ptIr","Oh,",
 "Oh, they're for new tenants. We already signed the contract, and now we're preparing for the handover.",
 "**Oh**, ↘↗ / they're for **NEW tenants**. ↘ We already **SIGNED the contract**, → / and now we're preparing for the **HANDOVER**. ↘",
 "**오**우, / 데어r f어r **뉴 테넌츠**. 위 올뤠디 **싸인d 더 컨트뤡트**, / 앤 나우 위r 프뤼페어링 f어r 더 **핸도우v어r**.",
 "아, 새 임차인들 것이에요. 계약은 이미 체결했고, 지금은 인계를 준비하고 있어요."),
("XhcHVk0qTczTLU1qImMj","Yeah,",
 "Yeah, no updates from them right now. They're getting ready for the handover on September seventh, so we've got a meeting scheduled with our engineer tomorrow at two thirty pm.",
 "Yeah, ↘↗ / no up**dates** from **them** right now. ↘ They're getting **rea**dy → / for the **hand**over → / on Sep**tem**ber **se**venth, → so we've got a **meet**ing **sche**duled → / with our engi**neer** → / to**mor**row → / at **TWO THIR**ty **PM**. ↘",
 "예, / 노우 업**데이**츠 f럼 **뎀** 롸잍 나우. / 데어r 게링 **레**리 / f어r 더 **핸**도우v어r / 온 셉**템**버r **쎄**v은쓰, / 소우 위v 가러 **미-**링 **스께**쥴d / 위드 아워r 엔쥐**니어r** / 투**마**로우 / 앹 **투 써**리 **피엠**.",
 "네, 지금은 그쪽에서 온 소식이 없어요. 9월 7일 인계를 준비하고 있어서, 내일 오후 2시 30분에 저희 엔지니어와 미팅이 잡혀 있어요."),
("d227P0pHGXRifu312eLA","So / need to → gotta",
 "So that week we gotta review the as-built plans and go over their interior drawings to check the work.",
 "**So** ↘↗ / that **week** ↘↗ / we **got**ta re**view** → / the **as**-built **plans** ↗ and go **o**ver their in**te**rior **DRAW**ings → / to check the **work**. ↓",
 "**쏘**우 / 댙 **위-ㅋ** / 위 **가**라 뤼**v유** / 디 **애z**-빌ㅌ **플랜z** / 앤드 고우 **오**우v어r 데어r 인**티**리어r **드로**잉z / 투 첵 더 **워-ㅋ**.",
 "그러니까 그 주에는 준공도면을 검토하고, 인테리어 도면을 살펴보면서 공사 상태를 확인해야 해요."),
("fIl6SQhjWxKzPUSXu1tA","Okay,",
 "Okay, I'll report it to my boss first, then get back to them.",
 "O**kay**, ↘↗ / I'll re**port** it to my **boss** first, ↗ then get **BACK** to them. ↘",
 "오우**케**이, / 아일 뤼**포rㅌ** 잍 투 마이 **바s** f어rsㅌ, / 덴 겥 **백** 투 뎀.",
 "네, 먼저 상사에게 보고하고, 그다음에 그쪽에 답을 주겠습니다."),
("nurljxfrVgAAAIzeO4w6","Oh, and",
 "Oh, and we had to prepare some undertaking letters for our tenants.",
 "**Oh**, and → / we **HAD** to prepare → / some undertaking **LETTERS** → / for our **TENANTS**. ↘",
 "**오**우, 앤d / 위 **해d** 터 프뤼페어r / 썸 언더r테이킹 **레러r-z** / f어r 아워r **테넌츠**.",
 "아, 그리고 임차인들에게 줄 이행각서를 준비해야 했어요."),
("tnQXRILBeROH8O6oPTHc","Well,",
 "Well, I'm not sure, but if he's not busy, he'll get back to me right away.",
 "**Well**, ↘↗ / I'm not **sure**, ↗ but if he's not **bu**sy, ↘↗ he'll get **BACK** to me right away. ↘",
 "**웰**, / 아임 낱 **슈어r**, / 벝 이f 히z 낱 **비**지, / 히을 겥 **백** 투 미 롸잍 어웨이.",
 "음, 확실하지는 않은데, 그 사람이 안 바쁘면 바로 답을 줄 거예요."),
("x0VAjbiiNUVZZHbzsua8","So / 발음 칸의 영문 혼입(vENT) 교정",
 "So we're trying to prevent any water pressure issues in the restrooms.",
 "**So** ↘↗ / we're trying to pre**VENT** → / any water pressure issues → / in the **RESTROOMS**. ↘",
 "**쏘**우 / 위r 츄라잉 터 프뤼**v엔ㅌ** / 애니 워러r 프뤠셔r 이슈-z / 인 더 **뤠s트룸-z**",
 "그러니까 화장실에 수압 문제가 생기지 않도록 예방하려고 합니다."),
("BBJvKGMmKatFmGps9ueR","Yeah,",
 "Yeah, three or four times a week. It's one of my favorite hobbies.",
 "Yeah, ↘↗ / **three** or **four** times a **week**. ↘ It's **one** of my **FA**vorite **ho**bbies. ↘",
 "예, / **쓰뤼** 오r **f오어r** 타임z 어 **위-ㅋ**. / 잍츠 **원** 어v 마이 **f에이**v릍 **하**비z.",
 "네, 일주일에 서너 번이요. 제가 제일 좋아하는 취미 중 하나예요."),
("JcRmtNiHWdMuZFRjA8lc","Well, / because → 'cause",
 "Well, when I run, I usually listen to upbeat music 'cause it helps me keep my energy up.",
 "**Well**, ↘↗ / when I **run**, ↘↗ I usually **lis**ten to **up**beat **mu**sic → 'cause it helps me keep my **E**nergy up. ↘",
 "**웰**, / 웬 아이 **뤈**, / 아이 유주얼리 **리**슨 투 **업**비-ㅌ **뮤**직 / 커z 잍 헬ps 미 킾 마이 **에**너rji 업.",
 "음, 뛸 때는 보통 신나는 음악을 들어요. 그래야 계속 힘이 나거든요."),
("iW2TD0sababIfBeL3RCV","So / kind of → kinda",
 "So after work I usually go for a run. When I'm running, it clears my head, kinda like meditation.",
 "**So** ↘↗ / after **work** ↘↗ / I usually go for a **run**. ↘ When I'm **run**ning, ↘↗ it **clears** my **head**, → / **kin**da like medi**TA**tion. ↘",
 "**쏘**우 / 애f터r **워-ㅋ** / 아이 유주얼리 고우 f어러 **뤈**. / 웬 아임 **뤄**닝, / 잍 **클리어rz** 마이 **헤d**, / **카**인더 라잌 메디**테**이션.",
 "그러니까 퇴근하고 나면 보통 달리기를 하러 가요. 뛰다 보면 머리가 맑아져서 명상 같은 느낌이에요."),
("zG0XqhNrOjLFijtbZao1","Well, / because → 'cause",
 "Well, I usually run alone, 'cause if I run with others, I end up following their pace. I'd rather keep my own.",
 "**Well**, ↘↗ / I usually **run** a**lone**, → '**cause** if I run with **o**thers, ↘↗ I end up **fo**llowing their **pace**. ↘ I'd **RA**ther keep my **own**. ↘",
 "**웰**, / 아이 유주얼리 **뤈** 어**로운**, / **커z** 이f 아이 뤈 위드 **어**더rz, / 아이 엔덥 **f아**로잉 데어r **페이s**. / 아이d **뢔**더r 킾 마이 **오운**.",
 "음, 저는 보통 혼자 뛰어요. 다른 사람이랑 뛰면 결국 그 사람 페이스를 따라가게 되거든요. 제 페이스를 지키는 게 나아요."),
("GwJaTirrQGSESiGAEaXa","Yeah,",
 "Yeah, I live in Bonifacio, so I usually run through the city streets. There's a park I like with a nice path, and it's right off the main street.",
 "Yeah, ↘↗ / I **live** in Boni**fa**cio, → so I usually **run** through the **ci**ty **streets**. ↘ There's a **park** I like → / with a **nice path**, ↗ and it's right **OFF** the main **street**. ↘",
 "예, / 아이 **리v** 인 보니**f아**시오우, / 소우 아이 유주얼리 **뤈** 쓰루 더 **씨**리 **스트뤼츠**. / 데어rz 어 **파rㅋ** 아이 라잌 / 위드 어 **나이s 패쓰**, / 앤드 잍츠 롸잍 **오f** 더 메인 **스트뤼ㅌ**.",
 "네, 저는 보니파시오에 살아서 보통 시내 길을 따라 뛰어요. 좋아하는 공원이 하나 있는데 길이 잘 돼 있고, 큰길 바로 옆이에요."),
("FbedYNcy6UFqzCENXIJP","Honestly,",
 "Honestly, the contractor's almost done with the job but they left a lot of stuff unfinished.",
 "**Hon**estly, ↘↗ / the con**tract**or's **al**most **done** → / with the **job** ↗ / but they **left** a **lot** of stuff → / un**FIN**ished. ↘",
 "**아**너s리, / 더 컨**추뤡**터rz **어ㄹ모우s던** / 위더 **좝** / 벗 데이 **레f트** 어 **랏** 어v s떠f / 언**f이니**쉬ㅌ.",
 "솔직히 시공사가 공사를 거의 끝냈는데, 마무리 안 된 게 많아요."),
("iYQ8PLzL2Fy2psemsii5","So / 리듬맵 when → When",
 "So first, we fixed the water pressure issue. When you turn on the faucet in the bathroom, there's barely any pressure coming out.",
 "**So** ↘↗ / **first**, ↘↗ / we **FIXED** the water **press**ure issue. ↘ When you **turn** on the **fau**cet → / in the **bath**room ↘↗ / there's **bare**ly any **PRESS**ure → / coming **out**. ↘",
 "**쏘**우 / **f어-rsㅌ**, / 위 **f익sㅌ** 더 워러r **프뤠**셔r 이슈-. **웬**뉴 **터r논** 더 **f어-**씻 / 인 더 **배ㅆ**루-ㅁ / 데어rz **베어r**리 에니 **프뤠셔r** / 커**미나웃**.",
 "그러니까 먼저 수압 문제를 고쳤어요. 화장실 수도꼭지를 틀면 물이 거의 안 나와요."),
("CaMqQZo7u1DRvYWjkKho","Honestly, / netflix → Netflix · 맨대문자 피크를 ** 로 감쌈",
 "Honestly, I felt relieved after I finished organizing, doing laundry, and cleaning the house. After that I watched Netflix. These days I'm really into Korean competition shows. Sometimes I put things off when I feel lazy, but I try to get it done every weekend.",
 "**Hon**estly, ↘↗ / I felt re**LIEVED** → / after I finished organizing, ↗ / doing laundry, ↗ / and cleaning the house. ↘ After that ↘↗ / I watched **NET**flix. ↘ These days ↘↗ / I'm really **IN**to → / Korean competition shows. ↘ Sometimes I put things **OFF** → / when I feel lazy, ↗ / but I try to get it done → / every weekend. ↘",
 "**아**너s리, / 아이 f엘ㅌ **뤼리-vd** / 애f터r 아이 f이니쉬ㅌ 오-r거나이z잉, / 두잉 러언쥬뤼, / 앤드 클리닝 더 하우s. 애f터r 댓 / 아이 워취ㅌ **넷f릭s**. 디-z 데이z / 아임 뤼얼리 **인투** / 커뤼-언 캄퍼티션 쇼우z. 썸타임z 아이 풋 씽z **어f** / 웬 아이 f이-ㄹ 레이z이, / 벗 아이 추롸이 투 게릿 던 / 에v리 위-켄드.",
 "솔직히 정리하고 빨래하고 청소까지 끝내고 나니까 마음이 놓였어. 그러고 나서 넷플릭스를 봤어. 요즘 한국 경쟁 예능에 푹 빠져 있어. 가끔 귀찮으면 미루긴 하는데, 주말마다 다 끝내려고는 해."),
("QHd4k8TfRC7tpkN5mr6X","So / because → 'cause · 맨대문자 피크를 ** 로 감쌈 · 발음 칸 깨진 글자 교정",
 "So this morning, I started organizing my stuff 'cause I'm moving soon. I went through things I don't use much, like my camera and some old gear. Before the move, I'm planning to sell a few of these items so the move is easier.",
 "**So** ↘↗ / this morning, ↘↗ / I started organizing my stuff → / 'cause I'm moving **SOON**. ↘ I went through things → / I don't use much, → / like my camera ↗ / and some old **GEAR**. ↘ Before the move, ↘↗ / I'm planning to sell → / a few of these items → / so the move is **EAS**ier. ↘",
 "**쏘**우 / 디s 모-r닝, / 아이 s따-r리d 오-r거나이z잉 마이 s떠f / 커z 아임 무-v잉 **쑤-ㄴ**. 아이 웬ㅌ 쓰루- 씽z / 아이 도운ㅌ 유-z 머취 / 라익 마이 캐므라 / 앤드 썸 오울d **기어r**. 비f오-r 더 무-v, / 아임 플래닝 투 쎌 / 어 f유- 어v 디-z 아이럼z / 쏘우 더 무-v 이z **이-z이어r**.",
 "그러니까 오늘 아침에 물건 정리를 시작했어, 곧 이사 가거든. 잘 안 쓰는 것들을 훑어봤어, 카메라랑 오래된 장비 같은 거. 이사 전에 몇 개를 팔 생각이야, 그래야 이사가 더 수월하니까."),
("kg1eWixtHuaDyvFDczfc","Honestly,",
 "Honestly, sometimes when I speak English, I feel flat, like I don't have any emotion.",
 "**Hon**estly, ↘↗ / sometimes when I **speak** English ↘↗ / I feel **FLAT** → / like I don't have any e**mo**tion ↘",
 "",
 "솔직히 가끔 영어로 말할 때 감정이 전혀 없는 것처럼 밋밋하게 느껴져요."),
]
SKIP4 = [("MIjidiow2nj69qS2uo8F","I actually run… 으로 actually 가 이미 있음")]
ALLOW_DIFF4 = set()
