# -*- coding: utf-8 -*-
# 필러·연결어 배치 5 (2026-09-29) — 회화 교정 4단계 30장 (121~150번째). 전부 발음 칸이 원래 비어 있다.
B5 = [
("n7TLdj4Yif2ETiWJkUSy","Oh,",
 "Oh, it reminds me of high school. We used to sing it together at noraebang.",
 "**Oh**, ↘↗ / it re**minds** me of high **SCHOOL** ↘ We **used** to **sing** it to**geth**er → / at **NORAEBANG** ↘","",
 "아, 그 노래를 들으면 고등학교 시절이 생각나요. 우리는 노래방에서 그 노래를 같이 부르곤 했어요."),
("q8UIG5wpNfirekxaHfA2","Well,",
 "Well, it was raining all day, so I needed to rest and listen to some music. It helped me calm down.",
 "**Well**, ↘↗ / it was **RAIN**ing all **day** → / so I **needed** to **rest** ↗ / and **listen** to some music ↘ It **helped** me **CALM** down ↘","",
 "음, 하루 종일 비가 와서 좀 쉬면서 음악을 들어야 했어요. 그게 마음을 진정시켜 줬어요."),
("Sa7ZwoiA8R7xVHtySsqy","Yeah,",
 "Yeah, it was raining all day, so I was craving something warm.",
 "Yeah, ↘↗ / it was **rain**ing all **DAY** → / so I was **crav**ing something **warm** ↘","",
 "네, 하루 종일 비가 와서 따뜻한 게 땡겼어요."),
("iMUDPDSjXdtL2WNlqhVy","Honestly,",
 "Honestly, it was raining all day, so I wanted noodles, and after eating, I felt satisfied.",
 "**Hon**estly, ↘↗ / it was **rain**ing all **DAY** → / so I **want**ed noodles → / and after **eat**ing ↘↗ / I felt **sat**isfied ↘","",
 "솔직히 하루 종일 비가 와서 면 요리가 먹고 싶었고, 먹고 나니 만족스러웠어요."),
("inQjAElT1YI3tom5r2Ek","honestly,",
 "I had the spice level two, but honestly, it wasn't too spicy for me.",
 "I had the **spice** level **TWO** ↗ / but **hon**estly, ↘↗ / it **wasn't** too **spi**cy for me ↘","",
 "저는 매운맛 2단계로 먹었는데, 솔직히 저한테는 그렇게 맵지 않았어요."),
("vH9k8hzkEtDBXZeivRgR","So",
 "So the staff helped me figure out what to order and how to order it.",
 "**So** ↘↗ / the staff **helped** me **fig**ure out → / what to **OR**der ↗ / and how to **or**der it ↘","",
 "그래서 직원이 뭘 주문할지, 또 어떻게 주문해야 할지 정하는 데 도움을 줬어요."),
("WkUjgMBAoT1RLmp8mtlT","Hmm,",
 "Hmm, I'm not sure about genres. I just watch whatever's funny.",
 "**Hmm**, ↘↗ / I'm not **sure** → / about **GEN**res ↘ I just **watch** → / what**EV**er's funny ↘","",
 "음, 장르는 잘 모르겠어요. 그냥 재미있는 건 뭐든 봐요."),
("ekcr4YzNs66icT67RSob","Yeah,",
 "Yeah, it's rainy season in the Philippines, so it's been pouring every day.",
 "Yeah, ↘↗ / it's **rain**y season → / in the **Phil**ippines → / so it's been **POUR**ing every day ↘","",
 "네, 필리핀은 지금 우기라서 매일 비가 쏟아지고 있어요."),
("qcryZHdMlbkTZ5MWHD80","I mean, / because → 'cause",
 "I mean, I think it's 'cause it's rainy season.",
 "I **mean**, ↘↗ / I **think** it's → / '**cause** it's **RAIN**y season ↘","",
 "그러니까, 우기라서 그런 것 같아요."),
("tWahbXBT1Ao4CSMqhj6F","You know,",
 "You know, when I watch a comedy and laugh a lot, I feel better.",
 "You **know**, ↘↗ / when I watch a **com**edy → / and **laugh** a lot ↘↗ / I feel **BET**ter ↘","",
 "있잖아요, 코미디를 보고 많이 웃으면 기분이 좋아져요."),
("vrBuasj63jAMC15bPgkx","Well,",
 "Well, I usually listen to music or watch a movie on Netflix.",
 "**Well**, ↘↗ / I **u**sually **lis**ten to music ↗ / or watch a movie → / on **NET**flix ↘","",
 "음, 저는 보통 음악을 듣거나 Netflix에서 영화를 봐요."),
("w8hPisHeMQ96Zh8RfNl4","Honestly,",
 "Honestly, when it rains, I feel a bit down.",
 "**Hon**estly, ↘↗ / when it **rains** ↘↗ / I feel a bit **DOWN** ↘","",
 "솔직히 비가 오면 기분이 좀 가라앉아요."),
("SBoPfI40eQYNg9z8Feod","You know,",
 "You know, when I run, it clears my head like meditation.",
 "You **know**, ↘↗ / when I **run** ↘↗ / it clears my **HEAD** → / like medi**ta**tion ↘","",
 "있잖아요, 달리면 명상처럼 머리가 맑아져요."),
("afXZTZoA3bv5maxTuYOX","I mean, / 뜻에만 있던 「달려서」 제거",
 "I mean, sometimes I push too hard and my legs feel strained afterward.",
 "I **mean**, ↘↗ / **some**times I push too **hard** → / and my legs feel **STRAINED** → / **af**terward ↘","",
 "그러니까, 가끔 너무 무리해서 나중에 다리에 무리가 간 느낌이 들어요."),
("w2ggZnzqQAEjX8O40MHO","Oh,",
 "Oh, I went for an eight-kilometer run after work.",
 "**Oh**, ↘↗ / I **went** for an **EIGHT**-kilometer run → / after **work** ↘","",
 "아, 퇴근 후에 8km를 달렸어요."),
("GHbtkWdkyBWnlbv3kSOc","Yeah, / 문장부호 보충 · tv → TV",
 "Yeah, I didn't do much after work. I just relaxed and watched a Korean TV show. I felt relieved.",
 "Yeah, ↘↗ / I didn't do **much** after **WORK**. ↘ I just re**laxed** and watched a Korean **TV** **show** ↘ I felt re**lieved** ↘","",
 "네, 퇴근 후에는 별거 안 했어요. 그냥 쉬면서 한국 TV 프로그램을 봤어요. 마음이 좀 놓였어요."),
("HPuHqVyWR0orhSYY4enC","Honestly, / tv → TV",
 "Honestly, I didn't do much. I just laid down on the couch and watched some Korean TV shows.",
 "**Hon**estly, ↘↗ / I didn't do **MUCH** ↘ I just **laid** down on the couch ↗ / and watched some Korean **TV** **shows** ↘","",
 "솔직히 별거 안 했어요. 그냥 소파에 누워서 한국 TV 프로그램을 좀 봤어요."),
("ZJfmsPXtZntE1Za2q2bP","So / have to → gotta",
 "So I gotta check my staff's tasks and give them instructions.",
 "**So** ↘↗ / I **got**ta **check** my staff's **TASKS** ↗ / and give them in**struc**tions ↘","",
 "그러니까 직원들의 업무를 확인하고 지시를 해야 해요."),
("iI9jQ77VvBLKYHGiaDe8","Honestly,",
 "Honestly, I had to fix some issues and help staff with their tasks, so it was hard to focus on my own work.",
 "**Hon**estly, ↘↗ / I had to **fix** some **ISSUES** ↗ / and help **staff** with their tasks → / so it was **hard** to focus on my own work ↘","",
 "솔직히 몇 가지 문제도 해결해야 했고 직원들 업무도 도와줘야 해서, 제 업무에 집중하기가 어려웠어요."),
("vQZiq8CKhU1FZy2rufcF","Yeah,",
 "Yeah, I just wanted to relax after work. I felt relieved.",
 "Yeah, ↘↗ / I just **want**ed to re**LAX** after work ↘ I felt re**LIEVED** ↘","",
 "네, 퇴근 후에는 그냥 쉬고 싶었어요. 마음이 후련했어요."),
("xckDNO0SkkuEfp89DDjI","Well,",
 "Well, it depends on the situation.",
 "**Well**, ↘↗ / it de**pends** on the situ**A**tion ↘","",
 "음, 상황에 따라 달라요."),
("1PZhFgRGnHZWAYKXNbcM","Honestly,",
 "Honestly, I'd love to go to Spain, especially Barcelona.",
 "**Hon**estly, ↘↗ / I'd **love** to go to **SPAIN**, → / especially Barce**lona** ↘","",
 "솔직히 스페인, 특히 Barcelona에 가보고 싶어."),
("8IYUL7EvwSaVl7VGAraI","So / 뜻에만 있던 「아침에」 제거",
 "So when I wake up I usually drink some coffee and do some stretching.",
 "**So** ↘↗ / when I **WAKE** up ↘↗ / I usually **drink** some **coffee** ↗ / and do some **stretch**ing ↘","",
 "그러니까 일어나면 보통 커피를 마시고 스트레칭을 해요."),
("NZmHsqyYMzDAx6lyMp7J","Yeah,",
 "Yeah, I work as a general manager for a Korean grocery store.",
 "Yeah, ↘↗ / I work as a **GEN**eral manager → / for a Korean **gro**cery store ↘","",
 "네, 저는 한국 식료품점에서 총괄 매니저로 일해요."),
("QoQM29kIx9vzj5C1x73X","Oh,",
 "Oh, I watched a Korean cooking competition.",
 "**Oh**, ↘↗ / I **watched** a Korean **COOK**ing competition ↘","",
 "아, 한국 요리 경연 프로그램을 봤어."),
("S2tOw7FD8RZIlY2NdyyW","Yeah,",
 "Yeah, it was an easy night. I just stayed in and watched TV.",
 "Yeah, ↘↗ / it was an **easy NIGHT** ↘ I just **stayed in** and watched **TV** ↘","",
 "네, 편하게 보낸 밤이었어. 그냥 집에 있으면서 TV 봤어."),
("gt3Mi9K5WhNpR1Jo6k68","Yeah,",
 "Yeah, yesterday was Sunday, but I didn't do much. I just relaxed and watched some Netflix.",
 "Yeah, ↘↗ / **YES**terday was **Sunday** ↗ / but I didn't do **much** → / I just re**laxed** and watched some **NET**flix ↘","",
 "네, 어제는 일요일이었는데 별거 안 했어. 그냥 쉬면서 Netflix 좀 봤어."),
("vmXotZ97o1lJz03EnEqR","Honestly,",
 "Honestly, I'd like to go with someone someday.",
 "**Hon**estly, ↘↗ / I'd **like** to go with **SOME**one someday ↘","",
 "솔직히 언젠가는 누군가와 같이 가보고 싶어."),
]
SKIP5 = [
 ("0zsQh9tNqhpn30tOIe17","문장 중간에 Actually, 가 이미 있음"),
 ("ZDv8gszmRGRakGh1S9sF","'cause 축약형이 이미 있음"),
]
