# -*- coding: utf-8 -*-
# 필러·연결어 배치 2 (2026-09-29) — 회화 교정 0~1단계 30장 (31~60번째)
B2 = [
("CYy4q2hhkFrxIRTOZBNV","Honestly, / because → 'cause ×2",
 "Honestly, I was pretty busy today, so I just wanted to get some rest after work. When I got home, I organized some stuff around the house 'cause I'm getting ready to move. I need to finish organizing everything this week, but I'm short on time 'cause I work every day.",
 "**Hon**estly, ↘↗ / I was **pret**ty **bus**y to**day** → / so I just **want**ed → / to get some **REST** → / after **work**. ↘ When I got **home**, ↘↗ / I **or**ganized some **stuff** → / around the **house** → / 'cause I'm → / getting **rea**dy to **MOVE**. ↘ I need to **fin**ish **or**ganizing → / **ev**erything this **week**, ↗ / but I'm **short** on **TIME** → / 'cause I **work** every **day**. ↘",
 "**아**너s리, / 아이 워z **프뤼**리 **비**z이 투**데이** / 쏘우 아이 저sㅌ **워**니d / 투 겟 썸 **뤠sㅌ** / 애f터r **워**-r크. 웨나이 갓 **호움** / 아이 **오**-r거나이zd 썸 **s떠**f / 어라운더 **하우s** / 커z 아임 / 게링 **뤠**디 투 **무**-v. 아이 니-투 **f이**니쉬 **오**-r거나이z잉 / **에**v리씽 디s **위**-ㅋ / 벗 아임 **쇼**-r론 **타임** / 커z 아이 **워**-r크 에v리 **데이**.",
 "솔직히 오늘 꽤 바빠서 퇴근하고 그냥 좀 쉬고 싶었어. 집에 와서는 이사 준비 중이라 집안 물건을 좀 정리했어. 이번 주에 정리를 다 끝내야 하는데 매일 일해서 시간이 부족해."),

("KbV35vZhMaDaBRZUUIQp","Actually,",
 "Hi, could you double-check something for me? Actually, I think I was charged the same fee twice on my account.",
 "**Hi**, ↘↗ / could you **dou**ble-**CHECK** something for me? ↗ **Ac**tually, ↘↗ / I **think** I was **charged** → / the same **fee twice** → / on my ac**count**. ↘",
 "하이, / 쿠쥬 **더**블**첵** 썸씽 f어r 미? **액**츄얼리, / 아이 **씽**ㅋ 아이 워z **촤**-rjd / 더 **쎄**임 **f이**- 트와이s / 온 마이 어**카**운ㅌ.",
 "안녕하세요, 하나만 확인해 주시겠어요? 사실 제 계좌에 같은 수수료가 두 번 청구된 것 같아요."),

("MjY1KTF5CO6XQz45UeNM","Yeah,",
 "Yeah, I understand, but I need that money soon. Is there any way you could speed it up?",
 "Yeah, ↘↗ / I under**stand**, ↗ / but I **need** that **MO**ney soon. ↘ Is there **an**y way → / you could **speed** it **up**? ↗",
 "예, / 아이 언더r**s땐**d, / 벗 아이 **니**-댓 **머**니 쑤-ㄴ. 이z 데어r **에**니 웨이 / 유 쿠d s**피**-릿업?",
 "네, 알겠어요, 그런데 그 돈이 곧 필요해서요. 좀 더 빨리 처리해 주실 방법이 있을까요?"),

("l21H8xQu3M9DIxihgBlq","Oh, and",
 "Oh, and the elevator's been broken since yesterday, so we called in a technician.",
 "**Oh**, and → / the e**le**vator's been **bro**ken → / since **yes**terday, → / so we **called** in a tech**NI**cian. ↘",
 "**오**우, 앤d / 디 **엘**러v에이러rz 빈 **브로**우큰 / 씬s **예**s터r데이, / 쏘우 위 **커어**ㄹd 이너 텍**니**션.",
 "아, 그리고 엘리베이터가 어제부터 고장이라서, 기사를 불렀어요."),

("nwuF9BEgbo5RxbUkJG9u","Yeah,",
 "Yeah, I'd like to open a new account. What do I need to bring?",
 "Yeah, ↘↗ / I'd **like** to **o**pen → / a **NEW** ac**count**. ↘ **What** do I need to **bring**? ↘",
 "예, / 아으d **라**익 투 **오**우픈 / 어 **누**- 어**카**운ㅌ. 왓 두 아이 니-투 브륑?",
 "네, 새 계좌를 개설하고 싶은데요. 뭘 가져와야 하나요?"),

("pVhKqSKiHwKJmEs0M0TO","Honestly, / since → 'cause",
 "Honestly, I'm worried the movers might damage some of my stuff. If they damage anything, I'll talk to the moving company. The insurance should cover it 'cause it came with the contract.",
 "**Hon**estly, ↘↗ / I'm **wor**ried → / the **mov**ers might **DAM**age → / some of my **stuff**. ↘ If they **dam**age **an**ything, ↘↗ / I'll **talk** to the **MOV**ing company. ↘ The in**sur**ance should **COV**er it → / 'cause it **came** → / with the **con**tract. ↘",
 "**아**너s리, / 아임 **워**-r리d / 더 **무**-v어rz 마잇 **대**미j / 써머v 마이 **s떠**f. 이f 데이 **대**미j **에**니씽 / 아으L **터억** 투 더 **무**-v잉 컴퍼니. 디 인**슈**런슈d **커**v어r 잇 / 커z 잇 **케임** / 위더 **컨**추뤡ㅌ.",
 "솔직히 이삿짐 업체 사람들이 내 물건 몇 개를 망가뜨릴까 봐 걱정돼. 뭔가 파손되면 이삿짐 업체에 얘기할 거야. 계약할 때 보험이 포함돼 있어서 보험으로 처리될 거야."),

("zfixG0dLf7z2TqatOWap","actually",
 "It was twenty thousand pesos, and I actually noticed it this morning when I was checking my banking app.",
 "It was **twen**ty **THOU**sand **pe**sos, → / and I **act**ually **no**ticed it this **mor**ning → / when I was **check**ing my **ban**king app. ↘",
 "잇 워z 트**웨**니 **싸**우전d **페**이쏘우z, / 앤드 아이 **액**츄얼리 **노**우티s 잇 디s **모**-r닝 / 웨 나이 워z **체**킹 마이 **뱅**킹앱.",
 "2만 페소였고, 사실 오늘 아침에 은행 앱을 확인하다가 알아챘어요."),

("DPw6RMB9omQfn3AGyNeb","Yeah, / kinda",
 "Yeah, I want it in the living room. It's just more comfortable for me. But I'm kinda worried the signal might be weak in my bedroom. Could you check it after you're done?",
 "Yeah, ↘↗ / I **want** it → / in the **LIV**ing room. ↘ It's just **more com**fortable → / for me. ↘ But I'm **kin**da **worr**ied ↗ / the **sig**nal might be **weak** → / in my **BED**room. ↘ **Could** you **check** it → / after you're **DONE**? ↗",
 "예, / 아이 **워**닛 / 인 더 **리**v잉 룸. 잇츠 저sㅌ **모**-r **컴**f터r블 / f어r 미. 벗 아임 **카**인더 **워**-리d / 더 **씩**늘 마잇 비 **위**-ㅋ / 인 마이 **베**d룸. **쿠**쥬 **체**킷 / 애f터r 유어r **던**?",
 "네, 거실에 놔 주세요. 그게 저한테 편해서요. 근데 침실 신호가 약할까 봐 좀 걱정이에요. 끝나고 한번 확인해 주실 수 있어요?"),

("GeabhMnZigi3oln7xrAl","Look,",
 "Look, if it's only half of what I'm paying for, that's a problem. So how do we get this fixed?",
 "**Look**, ↘↗ / if it's **on**ly **half** of → / what I'm **pay**ing for, ↘↗ / that's a **PROB**lem. ↘ So **how** do we → / get this **FIXED**? ↘",
 "**룩**, / 이f 잇츠 **오**운리 **해**f어v / 왓 아임 **페**이잉 f어r, / 댓처 **프라**블럼. 쏘우 **하**우 두 위 / 겟 디s **f익**sㅌ?",
 "저기, 내는 돈의 절반밖에 안 나온다면 그건 문제죠. 그럼 이거 어떻게 해결하죠?"),

("kFrTFHyIZosR2zCG2L8M","Oh, / 'Cause + gotta",
 "Oh, thanks, I appreciate that. Just let me know in advance when you're coming. 'Cause I gotta give the condo admin a heads up.",
 "**Oh**, ↘↗ / thanks, ↗ / I a**PPRE**ciate that. ↘ Just **let** me **know** → / in ad**vance** → / when you're **COM**ing. ↘ 'Cause I **got**ta **give** → / the **con**do **ad**min → / a **HEADS** up. ↘",
 "**오**우, / 쌩ks, / 아이 어**프뤼**쉬에잇댓. 저sㅌ **렛** 미 **노**우 / 인 어d**v앤**s / 웬 유어r **커**밍. 커z 아이 **가**라 **기**v / 더 **칸**도우 **애**d민 / 어 **헤**즈 업.",
 "아, 감사합니다. 오실 때 미리만 알려 주세요. 제가 콘도 관리실에 미리 얘기해 둬야 하거든요."),

("zkafXfHeRyUHmalubfji","Honestly,",
 "Honestly, two weeks is too long for me. I work from home, so I need this working now. Is there any way to speed it up?",
 "**Hon**estly, ↘↗ / **two weeks** is → / too **LONG** for me. ↘ I **work** from **home**, → / so I need this **WORK**ing now. ↘ Is there **an**y **way** → / to **SPEED** it up? ↗",
 "**아**너s리, / **투- 위**-ks 이z / 투- **러엉** f어r 미. 아이 **워**-rk f럼 **호**움, / 쏘우 아이 니-d 디s **워**r킹 나우. 이z 데어r **에**니 **웨**이 / 투 **s삐**-리럽?",
 "솔직히 2주는 저한테 너무 길어요. 집에서 일해서 지금 당장 되어야 해요. 좀 더 빨리 될 방법은 없을까요?"),

("XpYmXcZKZwtpRA6bSwIk","Anyway,",
 "Anyway, we hit a few construction delays this week. The contractor fell behind, so the handover got pushed to next week.",
 "**A**nyway, ↘↗ / we **hit** a few → / con**struc**tion de**LAYS** → / this **week**. ↘ The **con**tractor fell be**hind**, → / so the **hand**over → / got **PUSHED** to next **week**. ↘",
 "**에**니웨이, / 위 **힛** 어 f유- / 컨**s추뤅**션 디**레이z** / 디s **위-ㅋ**. 더 **칸**추뤡터r f엘 비**하인d**, / 쏘우 더 **핸**도우v어r / 갓 **푸쉬ㅌ** 투 넥sㅌ **위-ㅋ**.",
 "아무튼 이번 주에 공사 지연이 좀 있었어. 시공업체 일정이 밀려서 인수인계가 다음 주로 연기됐어."),

("rpozgze8HC5cJXdlxcC2","Yeah,",
 "Yeah, I told them we can't afford more delays, so I pushed them to restart tomorrow.",
 "Yeah, ↘↗ / I **told** them → / we can't af**ford** more de**lays**, → / so I **pushed** them → / to re**start** to**MOR**row. ↘",
 "예, / 아이 **토울d** 뎀 / 위 캔ㅌ 어**f오-rd** 모-r 디**레이z**, / 쏘우 아이 **푸쉬ㅌ** 뎀 / 투 뤼**s따-rㅌ** 터**마**로우.",
 "네, 더 이상 지연되면 안 된다고 말했고, 내일부터 다시 시작하도록 압박했어."),

("ls7cdVfXhWC0wM7wk9XO","So",
 "So could we start with the big stuff first, like the bed and the sofa?",
 "**So** ↘↗ / could we **start** → / with the **BIG** stuff **first**, → / like the **bed** and the **so**fa? ↗",
 "**쏘**우 / 쿠d 위 **s따**-rㅌ / 윋 더 **빅** s떠f **f어**-rsㅌ, / 라익 더 **베**d 앤드 더 **쏘우**f어?",
 "그럼 침대랑 소파 같은 큰 물건부터 먼저 시작할 수 있을까요?"),

("7HMVqC6TD2ZaXejN3o1F","'Cause",
 "Could you send someone today? 'Cause it's too hot to sleep without it.",
 "Could you **send** someone → / to**DAY**? ↗ 'Cause it's too **HOT** → / to **sleep** without it. ↘",
 "쿠쥬 **쎈d** 썸원 / 터**데이**? 커z 잇츠 투 **핫** / 투 **s리**-ㅍ 위다우릿.",
 "오늘 사람을 보내줄 수 있나요? 에어컨 없이는 너무 더워서 잠을 잘 수가 없거든요."),

("Y3HB78sA0l4jgtkujV56","So / Ac → AC",
 "So my AC is leaking. Water is dripping onto the floor.",
 "**So** ↘↗ / my A**C** is **LEAK**ing. ↘ **Wa**ter is **drip**ping → / onto the **FLOOR**. ↘",
 "**쏘**우 / 마이 에이**씨** 이s **리**-킹. **워**러r 이s **쥬뤼**핑 / 안투 더 **플로**-r.",
 "저기, 에어컨에서 물이 새고 있어요. 물이 바닥으로 떨어지고 있어요."),

("oy8E5yvO5CUcZ5Nt7PT2","Yeah,",
 "Yeah, I turned it off, so it's not dripping right now.",
 "Yeah, ↘↗ / I **turned** it **off**, → / so it's **not drip**ping → / right **NOW**. ↘",
 "예, / 아이 **터**-rn딧 **어어f**, / 쏘우 잇츠 **낫 쥬뤼**핑 / 롸잇 **나우**.",
 "네, 에어컨을 꺼놔서 지금은 물이 안 떨어져요."),

("fmkrRjzi2Ju6DVOzO2bt","going to → gonna",
 "We still haven't fixed the water pressure issue or replaced the glass yet. So I'm gonna push the contractor to confirm the schedule.",
 "We **STILL ha**ven't → / **fixed** the **wa**ter **pres**sure **is**sue ↗ / or re**placed** the **glass** yet. ↘ So I'm **gon**na **push** → / the **con**tractor → / to con**firm** the **SCHED**ule. ↘",
 "위 **s띨 해**v은ㅌ / **f익**s더 **워**러r **프뤠**셔r **이**슈 / 오r 뤼**플레이**s더 **글래**s 옛. 쏘우 아임 **거**너 **푸쉬** / 더 **컨**추뤡터r / 투 컨**f어**-rm 더 **s께**쥴.",
 "수압 문제도 아직 해결 못 했고, 유리 교체도 아직 안 됐어. 그래서 contractor한테 일정 확정하라고 강하게 요구할 거야."),

("q0zgYrjZyDNsIHJScfty","Honestly, / because → 'cause",
 "Honestly, I was pretty busy today 'cause we were preparing for the Metrobank handover.",
 "**Hon**estly, ↘↗ / I was **pret**ty **bu**sy to**day** → / 'cause we were pre**par**ing for → / the **Met**robank **HAND**over. ↘",
 "**아**너s리, / 아이 워s **프뤼**리 **비**z이 터**데이** / 커z 위 워r 프뤼**페어**r링 퍼r / 더 **메**추로우뱅ㅋ **핸**도우v어r.",
 "솔직히 오늘 꽤 바빴어. Metrobank 인수인계를 준비하고 있었거든."),

("zvktJt7LjDkQVHpLyD63","Honestly,",
 "Honestly, if they delay again, I'll bring in another contractor. I'm hoping we can wrap it up this week.",
 "**Hon**estly, ↘↗ / if they de**lay** a**gain**, ↘↗ / I'll bring **in** → / a**no**ther **CON**tractor. ↘ I'm **hop**ing ↗ / we can **wrap** it **up** → / this **WEEK**. ↘",
 "**아**너s리, / 이f 데이 디**레이** 어**겐**, / 아으L 브뤼**닌** / 어**너**더r **컨**추뤡터r. 아임 **호우**핑 / 위 큰 **뤠**피**럽** / 디s **위**-ㅋ.",
 "솔직히 또 지연되면 다른 contractor를 투입할 거야. 이번 주 안에 마무리할 수 있으면 좋겠어."),

("5io7IVofeLhqkxY5Hwxi","Hey,",
 "Hey, sorry to bother you, but we're in a meeting and we can't hear anything over the noise. Could you push it back an hour?",
 "**Hey**, ↘↗ / **Sor**ry to **both**er you, ↗ / but we're in a **meet**ing → / and we **can't hear an**ything → / over the **NOISE**. ↘ Could you **push** it **back** → / an **HOUR**? ↗",
 "**헤이**, / **싸**뤼 투 **바**더r 유, / 벗 위어r 인 어 **미**-링 / 앤드 위 **캔**ㅌ **히어**r **에**니씽 / 오우v어r 더 **노이**s. 쿠쥬 **푸**쉿 **백** / 언 **아워**r?",
 "저기요, 죄송한데 저희가 회의 중인데 소음 때문에 아무것도 안 들려요. 한 시간만 미뤄 주실 수 있을까요?"),

("CoOnPYvYJyz0bDUBDmZA","So",
 "So my order's about forty minutes late. I'd really appreciate it if you could check on it and let me know when it'll get here.",
 "**So** ↘↗ / my **or**der's a**bout** → / **FOR**ty **min**utes **late**. ↘ I'd **real**ly ap**pre**ciate it → / if you could **check** on it ↗ / and **let** me **KNOW** → / when it'll **get** here. ↘",
 "**쏘**우 / 마이 **오**-r더rs 어**바**웃 / **f오**-r리 **미**닛츠 **레**잇. 아으d **륄**리 어**프뤼**-쉬에이릿 / 이f 유 쿠d **체**커닛 / 앤드 **렛** 미 **노우** / 웬 이를 **겟** 히어r.",
 "저기, 주문한 게 40분 정도 늦었어요. 확인해 보시고 언제 도착하는지 알려 주시면 정말 감사하겠어요."),

("jklcung2EuB1m7PS77qn","so / double check → double-check",
 "Hi, so there's a minibar charge on my bill, but I never used it. I'd appreciate it if you could double-check.",
 "**Hi**, ↘↗ / **so** there's a **min**ibar **charge** → / on my **bill**, ↗ / but I **NEV**er **used** it. ↘ I'd ap**pre**ciate it → / if you could **dou**ble-**CHECK**. ↘",
 "**하이**, / **쏘**우 데어rs 어 **미**니바-r **차**-rj / 온 마이 **빌**, / 벗 아이 **네**v어r **유**-z딧. 아으d 어**프뤼**-쉬에이릿 / 이f 유 쿠d **더**버L **첵**.",
 "안녕하세요, 그게 청구서에 미니바 요금이 있는데 저는 전혀 안 썼어요. 확인 한 번만 해 주시면 감사하겠어요."),

("BFyors6i0ACASwob2HbT","actually",
 "I actually got udon instead. It's a different kind of noodle, so I think your staff mixed up the packages.",
 "I **act**ually **got** u**DON** in**stead**. ↘ It's a **dif**ferent kind of **noo**dle, → / so I think your **staff** → / **MIXED** up the **pack**ages. ↘",
 "아이 **액**츄얼리 **갓** 우**도운** 인s**떼**d. 잇처 **d이f**런ㅌ 카인더v **누**-를, / 쏘우 아이 씽큐어r **s때f** / **믹s**떱 더 **패**키쥐z.",
 "사실 우동이 대신 왔어요. 다른 종류의 면이라서, 직원분이 포장을 바꿔 담은 것 같아요."),

("KW161bNxa43m8u5vzzov","Yeah,",
 "Yeah, you don't need to prepare anything. But while they're inspecting your office, your staff probably won't be able to work.",
 "Yeah, ↘↗ / you **don't** need to pre**PARE** anything. ↘ But while they're in**spec**ting your **off**ice, ↘↗ / your **staff prob**ably → / **won't** be able to **WORK**. ↘",
 "예, / 유 **도운**ㅌ 니-투 프뤼**페어**r 에니씽. 벗 와일 데어r 인s**펙**팅 요r **아**f이s, / 요r **s때f 프롸**버블리 / **워운**ㅌ 비 에이블 터 **워**-rk.",
 "네, 따로 준비하실 건 없어요. 다만 점검하는 동안 직원분들이 아마 일을 못 하실 거예요."),

("OZOkit8ZwKkRLNnILVFl","actually",
 "Hi, can you check my order under Patrick? I ordered ramen, but I think you actually sent the wrong items.",
 "Hi, ↘↗ / can you **check** my **or**der / under **PA**trick? ↗ I **or**dered **ra**men, ↗ / but I think you **act**ually **sent** → / the **WRONG** items. ↘",
 "하이, / 캔뉴 **첵** 마이 **오**-r더r / 언더r **패**추뤽? 아이 **오**-r더rd **롸**-먼, / 벗 아이 씽큐 **액**츄얼리 **쎈**ㅌ / 더 **뤄어** 나이럼z.",
 "안녕하세요, Patrick 이름으로 된 주문 좀 확인해 주시겠어요? 라면을 주문했는데 사실 다른 물건이 온 것 같아요."),
]
SKIP2 = [
 ("oO4V3s5oVMRETBfS3njO","문장 중간에 but honestly, 가 이미 있음"),
 ("Rw2NACAq63nRAzFxir97","Hi, sorry to bother you 로 이미 말하는 호흡"),
 ("cP1En9SwSVdAOGvfSL2g","Hey, 로 이미 시작함"),
 ("7FCYqynfb9i74KUoW55z","문장 중간에 Honestly, 가 이미 있음"),
]
