# -*- coding: utf-8 -*-
# 필러·연결어 배치 6 (2026-09-29) — 회화 교정 4~5단계 33장 (151~183번째, 마지막)
B6 = [
("yCRXw9bXAnF4kvE7yEov","Honestly, / because → 'cause",
 "Honestly, I get stressed almost every day 'cause the construction company doesn't finish the work. So I end up solving the problem.",
 "**Hon**estly, ↘↗ / I get **stressed** almost every **DAY** → / 'cause the construction company doesn't **finish** the work ↘ So I **end up** solving the **PROB**lem ↘","",
 "솔직히 공사업체가 일을 끝내지 않아서 거의 매일 스트레스를 받아. 결국 그 문제를 내가 해결하게 돼."),
("R7XMTfjBZcuEWmLh5dUR","Yeah,",
 "Yeah, I just relaxed and watched some YouTube for a while. I didn't really feel like doing anything serious.",
 "Yeah, ↘↗ / I just re**LAXED** ↗ / and watched some **YOU**Tube for a while ↘ I didn't really feel like doing anything **SE**rious ↘","",
 "네, 그냥 쉬면서 한동안 YouTube를 봤어요. 딱히 뭔가 제대로 하고 싶은 기분은 아니었어요."),
("TGsv6Ttd6i6qUIow8l8v","I mean,",
 "I had some spicy instant noodles. I mean, I'm a big fan of noodles so I'd love some udon.",
 "I had some **SPI**cy instant noodles ↘ I **mean**, ↘↗ / I'm a big **FAN** of noodles → / so I'd **LOVE** some udon ↘","",
 "매운 인스턴트 누들을 먹었어요. 그러니까, 저는 면 요리를 정말 좋아해서 우동도 정말 먹고 싶어요."),
("YCSkt5RzL4w6fzzs5cNV","Oh,",
 "Oh, I caught up on a show.",
 "**Oh**, ↘↗ / I **caught up** on a **SHOW** ↘","",
 "아, 밀린 프로그램을 봤어."),
("fJLsd6PkMMurQ0kpAIGS","So / because → 'cause",
 "So today, we had a technical meeting with Aqualink and we prepared for the handover 'cause they'll start construction soon.",
 "**So** ↘↗ / today, we had a **TECH**nical meeting with Aqualink ↗ / and we pre**PARED** for the handover → / 'cause they'll start con**STRUC**tion soon ↘","",
 "그러니까 오늘 Aqualink와 기술 미팅을 했고, 곧 공사를 시작할 예정이라 인계 준비도 했어요."),
("piTRyfURzy69PwqP4Sdu","Honestly, / english → English",
 "Honestly, I think I'll just come home and study English or practice conversation with you like today.",
 "**Hon**estly, ↘↗ / I think I'll just come **HOME** ↗ / and study **ENG**lish ↗ / or practice conversation with you like to**DAY** ↘","",
 "솔직히 그냥 집에 와서 영어 공부를 하거나 오늘처럼 너와 회화 연습을 할 것 같아요."),
("vUK3i0sexPVjGd1aqYJj","Actually,",
 "Actually, I'd like to go to a Japanese restaurant tomorrow. I'm a big fan of noodles, so I'd love some udon.",
 "**Ac**tually, ↘↗ / I'd like to **GO** to a Japanese restaurant tomorrow → / I'm a big **FAN** of noodles → / so I'd **LOVE** some udon ↘","",
 "사실 내일 일식당에 가고 싶어요. 제가 면 요리를 정말 좋아해서 우동이 정말 먹고 싶어요."),
("2x3rVicHIzgAggBmb42H","Oh,",
 "Oh, nice work, Jam. You nailed it.",
 "**Oh**, ↘↗ / nice **WORK**, Jam → / You **NAILED** it ↘","",
 "오, 잘했어요, Jam. 정말 제대로 해냈어요."),
("6kp0jPoSxJPv6CKB436k","Well, / netflix → Netflix",
 "Well, when I relax I usually watch Netflix or some Korean shows. Sometimes I catch up on a show.",
 "**Well**, ↘↗ / when I re**LAX** ↘↗ / I usually watch **NET**flix or some Korean shows ↘ Sometimes I catch **UP** on a show ↘","",
 "음, 쉴 때는 보통 넷플릭스나 한국 프로그램을 봐요. 가끔 밀린 프로그램도 봐요."),
("E9qqbqc7qEDay217teLf","Yeah,",
 "Yeah, I understand your concern. At the same time, this is already the best rate we can offer, but we can offer you a rent-free period instead.",
 "Yeah, ↘↗ / I understand your con**CERN** → At the same **TIME** ↘↗ / this is already the best **RATE** we can offer ↗ / but we can offer you a rent-free period in**STEAD** ↘","",
 "네, 말씀하시는 부분은 이해합니다. 다만 현재 임대료가 저희가 드릴 수 있는 최선의 조건이고, 대신 렌트프리 기간을 제공해 드릴 수 있습니다."),
("EgslsVQJGfAWjwZbFdnz","Actually,",
 "Actually, I don't have a reservation. Do you have any rooms available tonight?",
 "**Ac**tually, ↘↗ / I don't have a reser**VA**tion ↘ Do you have any rooms available to**NIGHT**? ↗","",
 "사실 예약은 안 했어요. 오늘 밤 이용 가능한 방이 있나요?"),
("ddf4eb9c6p8YxqLOUr7t","Honestly,",
 "Honestly, I'd rather do it on a weekday but sometimes I feel lazy so I push it to the weekend.",
 "**Hon**estly, ↘↗ / I'd rather do it on a **WEEK**day ↗ / but sometimes I feel **LA**zy → / so I push it to the **WEEK**end ↘","",
 "솔직히 평일에 하는 게 더 좋긴 한데, 가끔 귀찮아서 주말로 미뤄요."),
("1sB8x4sKdTvnve27InYg","Yeah, / got → Got",
 "Yeah, got it. I'll get the report ready before the meeting.",
 "Yeah, ↘↗ / **GOT** it. ↘ I'll get the report **rea**dy → / before the **MEET**ing. ↘","",
 "네, 알겠습니다. 미팅 전에 보고서를 준비해둘게요."),
("RPwVWhI6DT1bQmTgSNpF","Hmm, / 쉼표 보충",
 "Hmm, I think it's September 7th, but I'll double-check and get back to you.",
 "**Hmm**, ↘↗ / I **think** it's September **7th** ↗ / but I'll **dou**ble-check ↗ / and get **BACK** to you. ↘","",
 "음, 9월 7일인 것 같은데, 다시 확인해서 알려드릴게요."),
("e45QKgP1H0qzymepVso0","Yeah, / 쉼표 보충",
 "Yeah, if that doesn't work, we can adjust. Just let me know.",
 "Yeah, ↘↗ / if that **does**n't work ↘↗ / we can ad**JUST**. ↘ Just let me **know**. ↘","",
 "네, 그게 안 되면 조정하면 됩니다. 그냥 알려주세요."),
("qqbY4neZkWUEQAQDzv6W","Hmm, / 쉼표 보충",
 "Hmm, I'm in the mood for something spicy, maybe noodles.",
 "**Hmm**, ↘↗ / I'm in the **mood** → / for something **spi**cy → / maybe **NOO**dles. ↘","",
 "음, 매콤한 게 당기네요. 아마 면 요리 같은 거요."),
("wwhOSfWXJSRU5z9cuUxK","Honestly,",
 "It took about two weeks. Honestly, way longer than it should've.",
 "It took about two **WEEKS**. ↘ **Hon**estly, ↘↗ / way longer than it should've. ↘",
 "잇 투커바웃 투 **위**-크s. **아**너s리, / 웨이 롱거r 대닛 슈러v",
 "2주 정도 걸렸어요. 솔직히 원래보다 훨씬 오래 걸린 거죠."),
("AetvNRvmxJYXk0cIiM5A","Oh,",
 "Oh, could I get the Wi-Fi password?",
 "**Oh**, ↘↗ / could I **GET** → / the Wi-Fi **password**? ↗",
 "**오**우, / 쿠다이 **겟** / 더 와이f아이 **패s워rㄷ**",
 "아, 와이파이 비밀번호 좀 알려주시겠어요?"),
("Q5FIhT9lbuzaARyoCttY","So",
 "So I was wondering if it's possible to move to a higher floor with a sea view.",
 "**So** ↘↗ / I was **WON**dering ↗ / if it's **possible** → / to move to a higher **FLOOR** → / with a sea **VIEW**. ↘",
 "**쏘**우 / 아이 워z **원**더r링 / 이f 잇s **파서블** / 터 무-v 터러 하이어r **f로어r** / 윋 어 씨- **v유-**",
 "저기, 바다가 보이는 높은 층으로 옮길 수 있을지 여쭤보고 싶었어요."),
("V1eA3L1TEWr1IhDJtreP","Oh,",
 "Oh, what time is breakfast?",
 "**Oh**, ↘↗ / what time is **BREAK**fast? ↘",
 "**오**우, / 왓 타임 이z **브렉f어sㅌ**",
 "아, 조식은 몇 시예요?"),
("zNSJ1P91O02yAdlru3M0","Okay,",
 "Okay, I'll double-check and get back to you.",
 "O**kay**, ↘↗ / I'll **dou**ble-check ↗ / and get **BACK** to you. ↘",
 "오우**케**이, / 아일 **더**블췤 / 앤드 겟 **백** 터유",
 "네, 다시 한번 확인하고 알려드릴게요."),
("8ciFAG2wHAArH8LzV5pP","Oh, and / 리듬맵 볼드 범위 교정",
 "Oh, and I sorted out some uniforms for the new staff.",
 "**Oh**, and → / I **SORT**ed out → / some **uniforms for the new staff**. ↘",
 "**오**우, 앤d / 아이 **쏘r**리d 아웃 / 썸 **유너f오rㅁz f어r 더 누 s태f**.",
 "아, 그리고 새로 온 직원들 유니폼을 정리했어요."),
("KxL50yEiyCxEN8CXIchh","Yeah, / 리듬맵 볼드 범위 교정",
 "Yeah, it was pretty slow today. I wasn't too busy.",
 "Yeah, ↘↗ / it was **PRET**ty slow today. ↘ I **wasn't too busy**. ↘",
 "예, / 잇 워z **프뤼**리 s로우 터데이. 아이 **워즌ㅌ 투 비지**.",
 "네, 오늘은 꽤 한가했어요. 그렇게 바쁘지 않았어요."),
("TEOtaPlzkYuDMWJ42hDE","Well,",
 "Well, I usually don't do much on weekends. I just relax and watch some Netflix, and sometimes I go for a run.",
 "**Well**, ↘↗ / I usually **don't** do much → / on **week**ends. ↘ I just re**lax** ↗ / and watch some **Net**flix, ↗ / and sometimes I go → / for a **RUN**. ↘",
 "**웰**, / 아이 유주얼리 **도운ㅌ** 두 머치 / 온 **위켄**즈. 아이 저슽 **릴랙스** / 앤 왓치 섬 **넽플릭스**, / 앤 섬타임즈 아이 고우 / 포r 어 **런**.",
 "음, 주말에는 보통 별로 안 해요. 그냥 쉬면서 넷플릭스를 보고, 가끔은 달리기를 하러 가요."),
("ZWrs3m93LfEIQKseP9oF","I mean,",
 "I mean, coffee helps me focus, or it keeps me sharp for a couple of hours.",
 "I **mean**, ↘↗ / coffee **helps me focus**, ↗ / or it **keeps me SHARP** → / for a couple of hours. ↘",
 "아이 **미**-ㄴ, / 커f피 **헬ㅍs 미 f오우커s**, / 오r 잇 **킵s 미 샤rㅍ** / f어r 러 커플 어v 아워rz.",
 "그러니까, 커피를 마시면 집중이 잘 되고, 두어 시간 정도는 정신이 또렷해져요."),
("ecVNiWi71x4Vlbe1BmaG","Honestly,",
 "Honestly, I usually get a little stressed every day, but today wasn't too bad.",
 "**Hon**estly, ↘↗ / I **usually get a little stressed every day**, ↗ / but today **wasn't too BAD**. ↘",
 "**아**너s리, / 아이 **유쥬얼리 게러 리를 s트뤠sㅌ 에v뤼 데이**, / 벗 터데이 **워즌ㅌ 투 배d**.",
 "솔직히 매일 조금씩 스트레스를 받는 편인데, 오늘은 그렇게 심하지 않았어요."),
("ewm7tKJUagumubtP9WVH","Well,",
 "Well, when I'm stressed, I usually drink some coffee.",
 "**Well**, ↘↗ / when I'm **STRESSED**, ↘↗ / I usually **drink some coffee**. ↘",
 "**웰**, / 웬 아임 **s트뤠sㅌ**, / 아이 **유쥬얼리 드륑ㅋ 썸 커f피**.",
 "음, 스트레스를 받으면 보통 커피를 마셔요."),
("ognn4EtrF4PICAUVfLxA","Yeah, / americano → Americano · 리듬맵 볼드 범위 교정",
 "Yeah, I usually get an Americano.",
 "Yeah, ↘↗ / I usually **get** an Ameri**CA**no. ↘",
 "예, / 아이 유쥬얼리 게런 어메뤼**카**-노우.",
 "네, 저는 보통 아메리카노를 마셔요."),
("fREn43wph2kZaV4HcM1j","Yeah,",
 "Yeah, I liked it there. As you know, Bangkok has a lot of tourist spots. I really liked the Thai massage and Thai food.",
 "Yeah, ↘↗ / I **liked** it there. ↘ As you **know**, **Bang**kok has a **LOT** of tourist spots. ↘ I really **liked** the Thai mas**sage** ↗ / and **THAI** food. ↘",
 "예, / 아이 **라익ㅌ** 잇 데어r. 애쥬 **노우**, **방**칵 해z **얼라러v** 투어리sㅌ s빳츠. 아이 뤼얼리 **라익ㅌ** 더 타이 마**싸**-지 / 앤드 **타이** f우-d.",
 "네, 거기 좋았어요. 아시다시피 방콕에는 관광지가 많잖아요. 타이 마사지랑 태국 음식이 정말 좋았어요."),
("hcrHtDuyXjsUIid3vxjY","You know,",
 "You know, I'm a big fan of noodles, so I'd love to try some pho or rice noodles. When I watched YouTube, I saw a lot of famous noodle dishes at local restaurants.",
 "You **know**, ↘↗ / I'm a **big** fan of **noo**dles, → so I'd **love** to try some **pho** ↗ / or **rice** noodles. ↘ When I **watched** YouTube, ↘↗ I saw a lot of **fa**mous **NOO**dle dishes → / at **lo**cal restaurants. ↘",
 "유 **노**우, / 아임 어 **빅** f앤 어v **누**-를z, 쏘우 아이d **러v** 투 추롸이 썸 **f어** / 어r **롸이s** 누-를z. 웬 아이 **와취ㅌ** 유-투-b, 아이 써어 얼라러v **f에이**머스 **누**-를 디쉬z / 앳 **로우**커ㄹ 뤠s추란츠.",
 "있잖아요, 제가 면 요리를 정말 좋아해서 쌀국수나 쌀면을 꼭 먹어보고 싶어요. YouTube를 봤을 때 현지 식당의 유명한 면 요리를 많이 봤거든요."),
("P0u2eMk8WIQU2vv53QqS","Yeah, / 쉼표 보충",
 "Yeah, if it's urgent, I'll just call them.",
 "Yeah, ↘↗ / if it's **UR**gent ↘↗ / I'll just **call** them ↘","",
 "네, 급한 일이면 그냥 전화할 거예요."),
]
SKIP6 = [
 ("BZKccGbNR9IA5d1P2Z2c","직원 지시문 — 규칙상 필러 적용 대상이 아니다(짧고 직접적으로)"),
 ("dzpoHG3x4uyOLC4OMonc","Hi, 로 이미 말하는 호흡"),
]
